### ISSUE TITLE
Investigate GetUser() NotFound error by adding additional logging

### ISSUE THREAD

**Issue by SaviorXTanren** [SaviorXTanren/mixer-mixitup#130]
```
3/25/2018 4:15:24 PM -07:00 - Mixer.Base.Util.RestServiceRequestException: Not Found
   at Mixer.Base.Services.RestServiceBase.<ProcessStringResponse>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.RestServiceBase.<ProcessResponse>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.RestServiceBase.<GetAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.UsersService.<GetUser>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.UsersService.<GetUser>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MixItUp.Base.Util.AsyncRunner.<RunAsync>d__1`1.MoveNext()
```

**Comment by SaviorXTanren** [comment]
Closing down as there is not enough information to action on currently.
