### ISSUE TITLE
Overlay images & text do not seem to be showing, even though they work when testing the commands

### ISSUE THREAD

**Issue by SaviorXTanren** [SaviorXTanren/mixer-mixitup#68]
Overlay images & text do not seem to be showing, even though they work when testing the commands

**Comment by SaviorXTanren** [comment]
Possible related exception:

System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at MixItUp.Base.Actions.OverlayAction.<PerformInternal>d__23.MoveNext()
