### ISSUE TITLE
GetStreamSessions - Mixer.Base.Util.RestServiceRequestException: first byte timeout

### ISSUE THREAD

**Issue by SaviorXTanren** [SaviorXTanren/mixer-mixitup#72]
Mixer.Base.Util.RestServiceRequestException: first byte timeout
   at Mixer.Base.Services.ServiceBase.<ProcessStringResponse>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.ServiceBase.<ProcessResponse>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.ServiceBase.<GetPagedAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.ChannelsService.<GetStreamSessions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MixItUp.Base.MixerAPI.MixerRequestWrapperBase.<RunAsync>d__4`1.MoveNext()

**Comment by SaviorXTanren** [comment]
Closing down as there is not enough information to action on currently.
