### ISSUE TITLE
Investigate continued issues with OBS WebSocket not detecting scene items

### ISSUE THREAD

**Issue by SaviorXTanren** [SaviorXTanren/mixer-mixitup#91]
OBSWebsocketDotNet.ErrorResponseException: specified scene item doesn't exist
   at OBSWebsocketDotNet.OBSWebsocket.SendRequest(String requestType, JObject additionalFields) in S:\Code\mixer-mixitup\obs-websocket-dotnet\OBSWebsocket.cs:line 330
   at OBSWebsocketDotNet.OBSWebsocket.SetSourceRender(String itemName, Boolean visible, String sceneName) in S:\Code\mixer-mixitup\obs-websocket-dotnet\OBSWebsocket_Requests.cs:line 91
   at MixItUp.OBS.OBSService.SetSourceRender(String source, Boolean isVisible) in S:\Code\mixer-mixitup\MixItUp.Desktop\Services\OBSService.cs:line 87

**Comment by SaviorXTanren** [comment]
Closing down as there is not enough information to action on currently.
